#!/bin/bash
# scripts/inventory_outputs.py answers "what did this run actually produce, and
# what shape is each file" so that plotting code is written against real column
# names instead of guessed ones.
#
# The failure this prevents is the one that ends with a plot script that never
# ran: a downstream step assumes report.tsv is comma-separated because it is
# called a report, or assumes the first line is the header when the first four
# lines are a '#' preamble whose LAST line is the header - which is exactly what
# nf-core's bbsplit stats files look like, and what a tool's .txt output that is
# really a TSV looks like. Extensions lie here; the bytes do not. So every
# assertion below is about the script reading the file rather than its name.
#
# It also guards the other half of the ticket: this script must stay blind to
# which pipeline produced the tree. There is no fixture here named after a tool,
# and nothing in the expected output names one.
#
# The fixture is built from scratch under mktemp -d. Nothing here touches the
# cluster: a machine that has never seen this site must pass.
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
S="$ROOT/scripts/inventory_outputs.py"
TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
fails=0

t() { # t <label> <expect-substring> <haystack>
  printf '%-58s ' "$1"
  if grep -qF -- "$2" <<<"$3"; then echo ok
  else echo "FAIL: lacks '$2'"; fails=$((fails+1)); fi
}
nt() { # nt <label> <forbidden-substring> <haystack>
  printf '%-58s ' "$1"
  if grep -qF -- "$2" <<<"$3"; then echo "FAIL: contains '$2'"; fails=$((fails+1))
  else echo ok; fi
}

# ---------------------------------------------------------------- the fixture
D="$TMP/results"
mkdir -p "$D/tables" "$D/meta" "$D/reports" "$D/blobs" "$D/deep/a/b/c" "$D/work" "$D/.hidden"

# A '#' preamble whose last line is the header, and a tool version banner above
# it. Counting the preamble as data, or the first '#' line as the header, are
# the two ways this file is normally got wrong.
{ printf '# generated by an assembler, v1.2.3\n'
  printf '# command: assemble --in reads --out asm\n'
  printf '#sample\tcontigs\tn50\tpct_complete\n'
  printf 'S1\t12\t41000\t99.4\n'
  printf 'S2\t9\t38500\t98.1\n'
  printf 'S3\t14\t44100\t99.9\n'
  printf 'S4\t11\t39900\t97.2\n'; } > "$D/tables/with_preamble.tsv"

# Comma-separated, quoted field containing the other delimiter - a sniffer that
# counts tabs before commas, or splits on whitespace, gets three columns here.
{ printf 'sample_id,condition,notes\n'
  printf 'S1,treated,"a note, with a comma"\n'
  printf 'S2,control,plain\n'
  printf 'S3,treated,also plain\n'; } > "$D/tables/plain.csv"

# The extension says text; the bytes say TSV. nf-core writes these constantly.
{ printf 'task_id\tname\tstatus\texit\n'
  printf '1\tALPHA\tCOMPLETED\t0\n'
  printf '2\tBETA\tCOMPLETED\t0\n'; } > "$D/tables/trace.txt"

# One column, no delimiter anywhere: must not be reported as a table with a
# fictitious separator.
printf 'line one\nline two\nline three\n' > "$D/tables/notes.txt"

printf '{"version": "1.0", "samples": {"S1": 3}, "warnings": []}\n' > "$D/meta/obj.json"
printf '[{"sample": "S1", "reads": 100}, {"sample": "S2", "reads": 200}, {"sample": "S3", "reads": 50}]\n' > "$D/meta/arr.json"
{ printf 'ALPHA_STEP:\n  alpha: 1.2.3\n'
  printf 'BETA_STEP:\n  beta: 4.5\n'
  printf 'Workflow:\n  Nextflow: 24.10.0\n'; } > "$D/meta/versions.yml"

printf '<html><body><h1>a report</h1></body></html>\n' > "$D/reports/report.html"
printf '%%PDF-1.4\n' > "$D/reports/report.pdf"

# A binary blob wearing a text extension - the NUL is what gives it away.
printf 'PK\003\004\000\000\000\000binary\000\000payload\000' > "$D/blobs/archive.txt"

# Over the threshold. Deliberately given a parseable header so that a script
# which ignored the threshold would produce column names and be caught.
long=$(printf 'x%.0s' $(seq 1 200))
{ printf 'a\tb\tc\n'; yes "$long"$'\t'"$long"$'\t'"$long" | head -3000; } > "$D/blobs/oversized.tsv"

# Obvious scratch, both kinds.
printf 'a\tb\nq\tr\n' > "$D/work/staged.tsv"
printf 'a\tb\nq\tr\n' > "$D/.hidden/cache.tsv"

printf 'depth_col\nv\n' > "$D/deep/a/b/c/buried.tsv"

# --------------------------------------------------------------- default run
out=$(python3 "$S" --max-mb 1 "$D" 2>&1); rc=$?
printf '%-58s ' "a results tree inventories cleanly"
[ "$rc" = 0 ] && echo ok || { echo "FAIL: rc=$rc <<$out>>"; fails=$((fails+1)); }

t "the preamble file is read as tab-separated"   "with_preamble.tsv" "$out"
t "its header comes from the last '#' line"      "pct_complete"      "$out"
t "and its first column is not '#sample'"        "sample"            "$out"
nt "the '#' is stripped from that header"        "#sample"           "$out"
printf '%-58s ' "preamble lines are not counted as rows"
if grep -E 'with_preamble\.tsv' -A3 <<<"$out" | grep -qE '\b4 rows\b'; then echo ok
else echo "FAIL: 4 data rows not reported <<$(grep -E 'with_preamble' -A3 <<<"$out")>>"; fails=$((fails+1)); fi

t "a csv reports its own columns"                "sample_id"         "$out"
t "and its quoted comma does not become a column" "condition"        "$out"
printf '%-58s ' "the quoted field stays one column"
if grep -E 'plain\.csv' -A3 <<<"$out" | grep -qF 'with a comma'; then
  echo "FAIL: split inside quotes"; fails=$((fails+1)); else echo ok; fi

t "a .txt that is really a tsv is detected as one" "task_id"          "$out"
t "one-column text is not given a delimiter"       "notes.txt"        "$out"

t "a json object lists its top-level keys"       "warnings"          "$out"
t "a json array reports its length"              "3"                 "$out"
t "and the keys of its first element"            "reads"             "$out"
t "a yaml lists its top-level keys"              "BETA_STEP"         "$out"
printf '%-58s ' "nested yaml keys are not promoted to top level"
if grep -E 'versions\.yml' -A3 <<<"$out" | grep -qE '\bbeta\b'; then
  echo "FAIL: nested key reported as top-level"; fails=$((fails+1)); else echo ok; fi

t "html is listed"                               "report.html"       "$out"
printf '%-58s ' "html is not parsed for columns"
if grep -E 'report\.html' -A2 <<<"$out" | grep -qiE 'column|rows'; then
  echo "FAIL: parsed an html file"; fails=$((fails+1)); else echo ok; fi
t "pdf is listed"                                "report.pdf"        "$out"

# ------------------------------------------------------------- what is skipped
t "a binary blob is named as skipped"            "archive.txt"       "$out"
t "and the reason says binary"                   "binary"            "$out"
t "an oversized file is named as skipped"        "oversized.tsv"     "$out"
printf '%-58s ' "and is not parsed despite parsing cleanly"
if grep -E 'oversized\.tsv' -A2 <<<"$out" | grep -qE '\brows\b'; then
  echo "FAIL: parsed past the size threshold"; fails=$((fails+1)); else echo ok; fi
t "the size threshold is stated"                 "--max-mb"          "$out"

nt "a work/ directory is not inventoried"        "staged.tsv"        "$out"
nt "a dotted directory is not inventoried"       "cache.tsv"         "$out"
t "but the run says scratch was skipped"         "scratch"           "$out"

# ------------------------------------------------------------------ max-depth
shallow=$(python3 "$S" --max-mb 1 --max-depth 2 "$D" 2>&1)
nt "--max-depth stops before a buried file"      "buried.tsv"        "$shallow"
t "and still reports the shallow ones"           "plain.csv"         "$shallow"

# ---------------------------------------------------------------------- --json
# Same facts, machine-readable. Asserted by parsing rather than by grep, because
# the whole point of the flag is that a consumer can rely on the structure.
js=$(python3 "$S" --max-mb 1 --json "$D" 2>&1)
probe=$(python3 - "$js" <<'PY'
import json, sys
d = json.loads(sys.argv[1])
by = {f["path"]: f for f in d["files"]}
sk = {f["path"]: f for f in d["skipped"]}
p = by["tables/with_preamble.tsv"]
print("DELIM_TAB" if p["delimiter"] == "\t" else "DELIM_" + repr(p["delimiter"]))
print("ROWS_%s" % p["rows"])
print("COLS_%s" % ",".join(p["columns"]))
print("CSV_%s" % by["tables/plain.csv"]["delimiter"])
print("JSONKEYS_%s" % ",".join(by["meta/obj.json"]["keys"]))
a = by["meta/arr.json"]
print("ARRLEN_%s" % a["length"])
print("ARRKEYS_%s" % ",".join(a["item_keys"]))
print("YAMLKEYS_%s" % ",".join(by["meta/versions.yml"]["keys"]))
print("HTMLKIND_%s" % by["reports/report.html"]["kind"])
print("HASSIZE" if by["reports/report.html"]["size"] > 0 else "NOSIZE")
print("SKIPBIN_%s" % sk["blobs/archive.txt"]["reason"])
print("SKIPBIG_%s" % sk["blobs/oversized.tsv"]["reason"])
print("ROOTOK" if d["root"].endswith("results") else "ROOTBAD")
PY
) || probe="PROBE FAILED: $probe"

t "--json is valid json with the same facts"     "ROOTOK"            "$probe"
t "delimiter is reported as an actual tab"       "DELIM_TAB"         "$probe"
t "row count survives the round trip"            "ROWS_4"            "$probe"
t "column names survive the round trip"          "COLS_sample,contigs,n50,pct_complete" "$probe"
t "csv delimiter is a comma"                     "CSV_,"             "$probe"
t "json object keys"                             "JSONKEYS_version,samples,warnings" "$probe"
t "json array length"                            "ARRLEN_3"          "$probe"
t "json array first-element keys"                "ARRKEYS_sample,reads" "$probe"
t "yaml top-level keys"                          "YAMLKEYS_ALPHA_STEP,BETA_STEP,Workflow" "$probe"
t "html is kind=opaque, size only"               "HTMLKIND_opaque"   "$probe"
t "and still carries a size"                     "HASSIZE"           "$probe"
t "binary skip reason is machine-readable"       "SKIPBIN_binary"    "$probe"
t "oversized skip reason is machine-readable"    "SKIPBIG_"          "$probe"

# --------------------------------------------------------------------- misuse
out=$(python3 "$S" "$TMP/not-a-thing" 2>&1); rc=$?
printf '%-58s ' "a missing directory is an error, not an empty report"
[ "$rc" != 0 ] && echo ok || { echo "FAIL: rc=0 <<$out>>"; fails=$((fails+1)); }

# ------------------------------------------------------- the interpreter fence
# PITFALLS 16d: /usr/bin/python3 here is RHEL's reserved interpreter, mode 750
# root:root. Executing this script directly under that PATH must explain itself
# rather than emit a bare `Permission denied`, which reads like a broken plugin.
mkdir -p "$TMP/fence"
printf '#!/bin/bash\necho "bash: /usr/bin/python3: Permission denied" >&2\nexit 126\n' > "$TMP/fence/python3"
chmod +x "$TMP/fence/python3"
out=$(PATH="$TMP/fence:$PATH" "$S" "$D" 2>&1); rc=$?
printf '%-58s ' "a fenced interpreter fails rather than half-runs"
[ "$rc" != 0 ] && echo ok || { echo "FAIL: exit 0 <<$out>>"; fails=$((fails+1)); }
t "and the guard names the way to a real python"  "module avail python" "$out"

echo
[ "$fails" = 0 ] && echo "all passed" || { echo "$fails failed"; exit 1; }
